### ISSUE TITLE
PHP-based admin tools

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/admin-tools#1]
- [x] PHPMyAdmin
- [x] phpRedisAdmin
- [x] phpinfo.php
- [x] zend Opcache Gui
- [ ] webgrind
- [ ] anemometer
- [x] Index for all admin tools https://github.com/EasyEngine/easyengine/issues/1118

**Comment by rahul286** [comment]
Depends on https://github.com/EasyEngine/easyengine/issues/1060

**Comment by mbtamuli** [comment]
We'll skip  `webgrind` for v4.0.0 as we're not targeting developer machines here. Only production machines.
